# Generated by Django 5.2.1 on 2025-05-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_athleteapi_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteapi',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='athleteapi',
            name='goalcalorie',
        ),
        migrations.RemoveField(
            model_name='athleteapi',
            name='goalweight',
        ),
        migrations.RemoveField(
            model_name='athleteapi',
            name='maintainance',
        ),
    ]
