# Generated by Django 5.2.1 on 2025-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteapi',
            name='bday',
            field=models.DateField(),
        ),
    ]
