# Generated by Django 5.2.1 on 2025-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_athleteapi_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteApi',
        ),
    ]
