# Generated by Django 5.2.1 on 2025-05-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=10)),
                ('bday', models.DateTimeField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('goalweight', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('maintainance', models.IntegerField()),
                ('goalcalorie', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['athlete'],
            },
        ),
    ]
