# Generated by Django 5.2.1 on 2025-07-09 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_remove_athlete_activity_remove_athlete_goalcalorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={},
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='bday',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='height',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='weight',
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
