# Generated by Django 5.2.1 on 2025-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_alter_athlete_options_remove_athlete_athlete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['athlete']},
        ),
        migrations.AddField(
            model_name='athlete',
            name='about_athlete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='athlete',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
