# Generated by Django 5.2.1 on 2025-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0004_alter_athlete_options_athlete_about_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='fitness_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='meal_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
