# Generated by Django 5.2.1 on 2025-05-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='goalcalorie',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='goalweight',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='maintainance',
        ),
    ]
